#!/bin/bash
docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

cp requirements.txt api

sudo docker build -t $DOCKER_USERNAME/fastapi:$TRAVIS_BRANCH -f docker/common/Dockerfile ./api

docker container run -d --name fastapi-backend -p 8000:8000 yannicnevhi/fastapi

curl http://fastapi-backend:8000/
