#!/bin/bash
docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

#docker build -t yannicnevhi/fastapi:latest -f docker/common/Dockerfile .

#docker container run --name fastapi-backend -p 8000:8000 yannicnevhi/fastapi

sudo rm /usr/local/bin/docker-compose
curl -L https://github.com/docker/compose/releases/download/1.4.2/docker-compose-`uname -s`-`uname -m` > docker-compose
chmod +x docker-compose
sudo mv docker-compose /usr/local/bin

cd docker/development

sudo docker-compose build

sudo docker-compose up -d

curl http://0.0.0.0:8000/