version: "3.3"

services:
  mongodb:
    image: mongo:2.4.14
    container_name: mongodb
    restart: always
    ports:
      - target: 27017
        published: 27017
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db

  fastapi:
    image: yannicnevhi/fastapi
    container_name: fastapi
    depends_on:
      - mongodb
    ports:
      - target: 8000
        published: 8000
    volumes:
      - type: bind
        source: ../../api
        target: /usr/src/api

volumes:
  mongo_data:


